# Generated by Django 4.1.3 on 2022-11-27 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SideProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("picture", models.ImageField(upload_to="picture/")),
                (
                    "name_text",
                    models.CharField(default="PatternCodding", max_length=20),
                ),
                (
                    "carreer_text",
                    models.CharField(default="Full stact developer", max_length=80),
                ),
                (
                    "email_text",
                    models.EmailField(
                        default="patterncodding@gmail.com", max_length=255
                    ),
                ),
                (
                    "number_text",
                    models.CharField(default="+2348101224630", max_length=15),
                ),
                ("birth_text", models.CharField(default="", max_length=20)),
                (
                    "location_text",
                    models.CharField(default="PatternCodding", max_length=20),
                ),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
