# Generated by Django 4.1.1 on 2022-11-27 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolioApp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="About",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("navbar", models.CharField(max_length=15)),
                ("about_heading", models.CharField(max_length=20)),
                ("text_1", models.TextField(blank=True, null=True)),
                ("text_2", models.TextField(blank=True, null=True)),
                ("duty_head", models.CharField(max_length=20)),
                ("duty_img", models.ImageField(upload_to="duty_image/")),
                ("duty_text", models.CharField(max_length=20)),
                ("duty_description", models.TextField()),
                ("testimony_header", models.CharField(default="", max_length=30)),
                ("testimony_image", models.ImageField(upload_to="testimony_image/")),
                ("testimony1", models.TextField(blank=True)),
                ("testimony_text2", models.TextField(blank=True)),
                ("client_header", models.CharField(default="", max_length=30)),
                ("client_image", models.ImageField(upload_to="client_image/")),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name="sideprofile",
            name="location_text",
            field=models.CharField(
                default="P3 Ishieke Campus villa Ebonyi state, Nigeria", max_length=50
            ),
        ),
    ]
