# Generated by Django 4.1.1 on 2022-11-27 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portfolioApp", "0002_about_alter_sideprofile_location_text"),
    ]

    operations = [
        migrations.RenameField(
            model_name="about", old_name="testimony1", new_name="testimoial_name",
        ),
        migrations.RenameField(
            model_name="about", old_name="testimony_text2", new_name="testimony_text",
        ),
    ]
