# Generated by Django 4.1.1 on 2022-11-28 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolioApp", "0003_rename_testimony1_about_testimoial_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Navbar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("navbar", models.CharField(max_length=15)),
            ],
        ),
        migrations.RemoveField(model_name="about", name="navbar",),
    ]
