# Generated by Django 4.1.1 on 2022-11-28 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolioApp", "0007_remove_blog_blog_header"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=255)),
                ("email", models.EmailField(default="", max_length=255)),
                ("messages", models.TextField(blank=True, default="", null=True)),
            ],
        ),
    ]
