# Generated by Django 4.1.1 on 2022-11-28 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portfolioApp", "0008_contact"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contact", old_name="username", new_name="fulname",
        ),
    ]
