# Generated by Django 4.1.1 on 2022-11-29 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolioApp", "0011_resume_alter_contact_messages"),
    ]

    operations = [
        migrations.CreateModel(
            name="Education",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("school", models.CharField(default="", max_length=50)),
                ("educ_date", models.CharField(default="2018-2022", max_length=15)),
                ("edu_description", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Experience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("experience_name", models.CharField(default="", max_length=50)),
                ("exp_year", models.CharField(default="2018-2022", max_length=20)),
                ("exp_description", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("skills_name", models.CharField(default="", max_length=50)),
                ("skills_perc", models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(name="Resume",),
    ]
