# Generated by Django 4.1.1 on 2022-11-30 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolioApp", "0012_education_experience_skill_delete_resume"),
    ]

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("client_header", models.CharField(default="", max_length=30)),
                ("client_image", models.ImageField(upload_to="client_image/")),
            ],
        ),
        migrations.CreateModel(
            name="Duty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("duty_img", models.ImageField(upload_to="duty_image/")),
                ("duty_text", models.CharField(max_length=20)),
                ("duty_description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Testimonials",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("testimony_image", models.ImageField(upload_to="testimony_image/")),
                ("testimoial_name", models.TextField(blank=True)),
                ("testimony_text", models.TextField(blank=True)),
            ],
        ),
        migrations.RemoveField(model_name="about", name="client_header",),
        migrations.RemoveField(model_name="about", name="client_image",),
        migrations.RemoveField(model_name="about", name="duty_description",),
        migrations.RemoveField(model_name="about", name="duty_head",),
        migrations.RemoveField(model_name="about", name="duty_img",),
        migrations.RemoveField(model_name="about", name="duty_text",),
        migrations.RemoveField(model_name="about", name="testimoial_name",),
        migrations.RemoveField(model_name="about", name="testimony_header",),
        migrations.RemoveField(model_name="about", name="testimony_image",),
        migrations.RemoveField(model_name="about", name="testimony_text",),
    ]
