# Generated by Django 4.1.1 on 2022-11-30 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "portfolioApp",
            "0014_testimonials_testimoial_date_alter_duty_duty_text_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(model_name="client", name="client_header",),
    ]
