# Generated by Django 4.1.1 on 2022-12-02 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolioApp", "0015_remove_client_client_header"),
    ]

    operations = [
        migrations.CreateModel(
            name="Portfolio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("portolio_img", models.ImageField(upload_to="portfolio_img/")),
                ("portolio_name", models.CharField(default="", max_length=50)),
                ("portolio_desc", models.CharField(default="", max_length=50)),
                ("uploaded", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
